<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FiveECharacterGenerator.Application\FiveECharacterGenerator.Application.csproj" />
    <ProjectReference Include="..\FiveECharacterGenerator.Persistence\FiveECharacterGenerator.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
